import { Cards } from "../Cards";

import { ProjectsContainer, ProjectsContent } from "./styles";

export function Projects() {
  return (
    <ProjectsContainer>
      <h1>{"<Projetos>"}</h1>
      <ProjectsContent>
        <Cards
          colorTop="projects"
          type="challenge"
          title="Upnid"
          stack="frontend"
          hasReact
          hasNetlify
          hasStyledComponents
          hasLink
          hasDeploy
          iconButton={"GitHub"}
          deploy={"https://upnid-uprace-murilojssilva.netlify.app/"}
          href="https://github.com/murilojssilva/desafio-pagcom"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="TruckPag"
          stack="frontend"
          hasReact
          hasStyledComponents
          hasTypescript
          hasJest
          hasNetlify
          hasLink
          hasDeploy
          deploy="https://desafio-truckpag.netlify.app/"
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/desafio-truckpag"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Vizir"
          stack="frontend"
          hasReact
          hasTypescript
          hasVercel
          hasNextJS
          hasSASS
          hasLink
          hasDeploy
          deploy="https://murilosilva-desafio-vizir.vercel.app/"
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/desafio-vizir"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Intelie - Chart"
          stack="frontend"
          hasReact
          hasNetlify
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/intelie-chart"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Intelie - Pokemon"
          stack="frontend"
          hasReact
          hasNetlify
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/pokemon-intelie"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Pagcom"
          stack="frontend"
          hasReact
          hasTypescript
          hasStyledComponents
          hasVercel
          hasAxios
          hasVite
          hasLink
          hasDeploy
          deploy="https://desafio-pagcom.vercel.app/"
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/desafio-pagcom"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Codeleap"
          stack="frontend"
          hasReact
          hasTypescript
          hasStyledComponents
          hasVite
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/codeleap-challenge"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Workana Test"
          stack="frontend"
          hasReact
          hasJest
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/workana-test"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - DT Money"
          stack="frontend"
          hasReact
          hasTypescript
          hasStyledComponents
          hasRadix
          hasZod
          hasPhosphor
          hasVite
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-dt-money"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Coffee Delivery"
          stack="frontend"
          hasReact
          hasTypescript
          hasStyledComponents
          hasPhosphor
          hasVite
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-reactjs-challenge-2-coffee-delivery"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Ignews"
          stack="frontend"
          hasReact
          hasTypescript
          hasStyledComponents
          hasNextJS
          hasSASS
          hasFaunaDB
          hasAxios
          hasStripe
          hasLink
          hasDeploy
          iconButton={"GitHub"}
          deploy="https://murilojssilva-ignite-deploy-application.netlify.app/"
          href="https://github.com/murilojssilva/ignite-ignews"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Otimizando a aplicação"
          stack="frontend"
          hasReact
          hasTypescript
          hasAxios
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-otimizando-aplicacao"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Fundamentos ReactJS"
          stack="frontend"
          hasReact
          hasPhosphor
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/01-fundamentos-reactjs-ignite"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Upload de imagens"
          hasReact
          stack="frontend"
          hasTypescript
          hasNextJS
          hasChakra
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-upload-de-imagens"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - SpaceTraveling"
          stack="frontend"
          hasReact
          hasSASS
          hasJest
          hasTypescript
          hasNextJS
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/04-spacetraveling"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Todos"
          stack="mobile"
          hasReactNative
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-template-react-native-todos"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Go Finance"
          stack="mobile"
          hasReactNative
          hasTypescript
          hasStyledComponents
          hasExpo
          hasYup
          hasVictoryNative
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-react-native-gofinance"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Savepass"
          stack="mobile"
          hasReactNative
          hasTypescript
          hasStyledComponents
          hasExpo
          hasYup
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-react-native-capter-ii-desafio-01"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Stream Data"
          stack="mobile"
          hasReactNative
          hasTypescript
          hasStyledComponents
          hasExpo
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/desafio-02-ignite-react-native-chapter-ii"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - My Skills"
          stack="mobile"
          hasReactNative
          hasTypescript
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-react-native-myskills"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Origamid - Ranek"
          stack="frontend"
          hasLink
          hasVue
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/origamid-ranek"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Origamid - Techno"
          stack="frontend"
          hasLink
          hasVue
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/origamid-techno"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Origamid - CSS com SASS"
          stack="frontend"
          hasSASS
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/origamid-sass"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Origamid - Validar CPF"
          stack="frontend"
          hasJavascript
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/origamid-validar-cpfs"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Origamid - Limpar CPFs"
          stack="frontend"
          hasJavascript
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/origamid-limpar-cpfs"
        />

        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Origamid - Slide"
          stack="frontend"
          hasJavascript
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/origamid-slide"
        />

        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Origamid - Brafé 1 (Grid)"
          stack="frontend"
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/origamid-brafe1-grid"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Origamid - Brafé 1 (Puro)"
          stack="frontend"
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/origamid-brafe1-puro"
        />
        <Cards
          colorTop="projects"
          type="academic"
          title="Sistema ACESSO"
          stack="mobile"
          hasReactNative
          hasTypescript
          hasStyledComponents
          hasFirebase
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/KleberCaldas/acesso"
          inDevelopment
        />
        <Cards
          colorTop="projects"
          type="academic"
          stack="fullstack"
          title="Instituto de Matemática e Estatística (UERJ)"
          hasReact
          hasTypescript
          hasStyledComponents
          hasJest
          hasGraphQL
          hasLink
          iconButton={"GitLab"}
          href="https://gitlab.com/imeuerj/site-ime"
        />
        <Cards
          colorTop="projects"
          type="personal"
          title="ResolveLogo (Front End)"
          stack="frontend"
          hasReact
          hasSASS
          hasRedux
          hasLink
          hasDeploy
          deploy="https://resolvelogo.netlify.app/"
          iconButton={"GitLab"}
          href="https://gitlab.com/murilojssilva/resolvelogoweb"
        />
        <Cards
          colorTop="projects"
          type="personal"
          title="ResolveLogo (Back End)"
          stack="backend"
          hasNodeJS
          hasExpress
          hasHeroku
          hasJWT
          hasMongoDB
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/resolvelogo-backend"
        />
      </ProjectsContent>
      <h1>{"</Projetos>"}</h1>
    </ProjectsContainer>
  );
}
