import { Cards } from "../Cards";

import { ProjectsContainer, ProjectsContent } from "./styles";

export function Projects() {
  return (
    <ProjectsContainer>
      <h1>{"<Projetos>"}</h1>
      <ProjectsContent>
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - DT Money"
          hasReact
          hasTypescript
          hasStyledComponents
          hasRadix
          hasZod
          stack="frontend"
          hasPhosphor
          hasVite
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-dt-money"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Coffee Delivery"
          hasReact
          hasTypescript
          hasStyledComponents
          hasPhosphor
          stack="frontend"
          hasVite
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-reactjs-challenge-2-coffee-delivery"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Go Finance"
          hasReactNative
          hasTypescript
          stack="mobile"
          hasStyledComponents
          hasExpo
          hasYup
          hasVictoryNative
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-react-native-gofinance"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Upload de imagens"
          hasReact
          stack="frontend"
          hasTypescript
          hasNextJS
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/ignite-upload-de-imagens"
        />
        <Cards
          colorTop="projects"
          type="bootcamp"
          title="Ignite - Stream Data"
          stack="mobile"
          hasReactNative
          hasTypescript
          hasStyledComponents
          hasExpo
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/desafio-02-ignite-react-native-chapter-ii"
        />
        <Cards
          colorTop="projects"
          type="academic"
          title="Sistema ACESSO"
          stack="mobile"
          hasReactNative
          hasTypescript
          hasStyledComponents
          hasFirebase
          inDevelopment
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Desafio Pagcom"
          stack="frontend"
          hasReact
          hasTypescript
          hasStyledComponents
          hasVercel
          hasAxios
          hasVite
          hasLink
          hasDeploy
          deploy="https://desafio-pagcom.vercel.app/"
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/desafio-pagcom"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Workana Test"
          stack="frontend"
          hasReact
          hasJest
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/workana-test"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Desafio Upnid"
          stack="frontend"
          hasReact
          hasNetlify
          hasStyledComponents
          hasLink
          hasDeploy
          iconButton={"GitHub"}
          deploy={"https://upnid-uprace-murilojssilva.netlify.app/"}
          href="https://github.com/murilojssilva/desafio-pagcom"
        />
        <Cards
          colorTop="projects"
          type="academic"
          stack="fullstack"
          title="Instituto de Matemática e Estatística (UERJ)"
          hasReact
          hasTypescript
          hasStyledComponents
          hasJest
          hasGraphQL
          hasLink
          iconButton={"GitLab"}
          href="https://gitlab.com/imeuerj/site-ime"
        />
        <Cards
          colorTop="projects"
          type="personal"
          title="ResolveLogo (Front End)"
          stack="frontend"
          hasReact
          hasSASS
          hasRedux
          hasLink
          hasDeploy
          deploy="https://resolvelogo.netlify.app/"
          iconButton={"GitLab"}
          href="https://gitlab.com/murilojssilva/resolvelogoweb"
        />
        <Cards
          colorTop="projects"
          type="personal"
          title="ResolveLogo (Back End)"
          stack="backend"
          hasNodeJS
          hasExpress
          hasHeroku
          hasJWT
          hasMongoDB
          hasLink
          hasDeploy
          deploy="https://desafio-truckpag.netlify.app/"
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/resolvelogobackend"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="TruckPag"
          stack="frontend"
          hasReact
          hasStyledComponents
          hasTypescript
          hasJest
          hasNetlify
          hasLink
          hasDeploy
          deploy="https://desafio-truckpag.netlify.app/"
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/desafio-truckpag"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Vizir"
          stack="frontend"
          hasReact
          hasTypescript
          hasVercel
          hasNextJS
          hasSASS
          hasLink
          hasDeploy
          deploy="https://murilosilva-desafio-vizir.vercel.app/"
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/desafio-vizir"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Intelie - Chart"
          stack="frontend"
          hasReact
          hasNetlify
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/intelie-chart"
        />
        <Cards
          colorTop="projects"
          type="challenge"
          title="Intelie - Pokemon"
          stack="frontend"
          hasReact
          hasNetlify
          hasLink
          iconButton={"GitHub"}
          href="https://github.com/murilojssilva/pokemon-intelie"
        />
      </ProjectsContent>
      <h1>{"</Projetos>"}</h1>
    </ProjectsContainer>
  );
}
